name: pull_request

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: lint
    uses: csbasil/tfrmaker/.github/workflows/lint.yml@main

  test:
    name: test
    needs: lint
    uses: csbasil/tfrmaker/.github/workflows/test.yml@main

  build:
    name: build
    needs: test
    uses: csbasil/tfrmaker/.github/workflows/build.yml@main
